# remove infra

#####################################################
#                                                   # 
# This file is located in the Azure repository and  #
# must be pulled via the git upstream.              #  
#                                                   #  
# Don't make any changes to this file outside       # 
# the Azure repository, otherwise merge conflicts   #
# will occur.                                       #
#                                                   #
#####################################################

trigger: none
pr: none

stages:
- stage: RemoveApp
  displayName: Remove App
  jobs:
  - job: RemoveApp
    displayName: Remove App
    pool:
        name: $(Pool)
        ${{ if eq(variables.Pool, 'Azure Pipelines') }}:
        vmImage: $(Image)
    steps:
    - template: templates\create deployment package on agent.yml
    - template: templates\remove app.yml
      parameters:
        Subscription: $(Subscription)
        ResourceGroup: $(ResourceGroup)
        DeploymentMethod: $(DeploymentMethod)